#!/bin/bash

THEME=$1

# Symlink GTK themes if they exist
if [[ -e "~/.config/omarchy/themes/$THEME/gtk.css" ]]; then
  ln -nsf ~/.config/omarchy/themes/$THEME/gtk.css ~/.config/gtk-3.0/gtk.css
  ln -nsf ~/.config/omarchy/themes/$THEME/gtk.css ~/.config/gtk-4.0/gtk.css
fi


# Note: theme-set.d/* scripts are NOT run from here. omarchy-hook already
# runs everything in theme-set.d/ natively (with the theme name forwarded)
# after this file executes, so looping over it here would run each script
# twice, once without the theme-name argument.


