[theme.custom]
accent = "{{ accent }}"
panel_bg = "{{ background }}"
text = "{{ foreground }}"
subtext0 = "{{ bright_foreground }}"
overlay0 = "{{ muted }}"
red = "{{ red }}"
green = "{{ green }}"
yellow = "{{ yellow }}"
blue = "{{ blue }}"
mauve = "{{ magenta }}"
teal = "{{ cyan }}"
